<?php

declare(strict_types = 1);

require __DIR__ . '/all.php';
require __DIR__ . '/any.php';
require __DIR__ . '/apply.php';
require __DIR__ . '/assoc.php';
require __DIR__ . '/butlast.php';
require __DIR__ . '/complement.php';
require __DIR__ . '/compose.php';
require __DIR__ . '/constant.php';
require __DIR__ . '/dissoc.php';
require __DIR__ . '/do_if.php';
require __DIR__ . '/each.php';
require __DIR__ . '/filter.php';
require __DIR__ . '/filter_fresh.php';
require __DIR__ . '/filter_null.php';
require __DIR__ . '/first.php';
require __DIR__ . '/flat_map.php';
require __DIR__ . '/flatten.php';
require __DIR__ . '/get.php';
require __DIR__ . '/get_each.php';
require __DIR__ . '/get_in.php';
require __DIR__ . '/group_by.php';
require __DIR__ . '/key.php';
require __DIR__ . '/identity.php';
require __DIR__ . '/instance_of.php';
require __DIR__ . '/last.php';
require __DIR__ . '/map.php';
require __DIR__ . '/memoize.php';
require __DIR__ . '/not.php';
require __DIR__ . '/partial.php';
require __DIR__ . '/partition.php';
require __DIR__ . '/pipe.php';
require __DIR__ . '/reduce.php';
require __DIR__ . '/reindex.php';
require __DIR__ . '/repeat.php';
require __DIR__ . '/rest.php';
require __DIR__ . '/reverse.php';
require __DIR__ . '/search.php';
require __DIR__ . '/some.php';
require __DIR__ . '/sort.php';
require __DIR__ . '/to_array.php';
